class CountryOption {
  const CountryOption({required this.code, required this.name, required this.flag});

  /// ISO 3166-1 alpha-2, e.g. "BR"
  final String code;

  /// Full English name, e.g. "Brazil"
  final String name;

  /// Emoji flag, e.g. "🇧🇷"
  final String flag;
}

/// All countries sorted alphabetically by name.
const List<CountryOption> kCountries = [
  CountryOption(code: 'AF', name: 'Afghanistan', flag: '🇦🇫'),
  CountryOption(code: 'AL', name: 'Albania', flag: '🇦🇱'),
  CountryOption(code: 'DZ', name: 'Algeria', flag: '🇩🇿'),
  CountryOption(code: 'AD', name: 'Andorra', flag: '🇦🇩'),
  CountryOption(code: 'AO', name: 'Angola', flag: '🇦🇴'),
  CountryOption(code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬'),
  CountryOption(code: 'AR', name: 'Argentina', flag: '🇦🇷'),
  CountryOption(code: 'AM', name: 'Armenia', flag: '🇦🇲'),
  CountryOption(code: 'AU', name: 'Australia', flag: '🇦🇺'),
  CountryOption(code: 'AT', name: 'Austria', flag: '🇦🇹'),
  CountryOption(code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿'),
  CountryOption(code: 'BS', name: 'Bahamas', flag: '🇧🇸'),
  CountryOption(code: 'BH', name: 'Bahrain', flag: '🇧🇭'),
  CountryOption(code: 'BD', name: 'Bangladesh', flag: '🇧🇩'),
  CountryOption(code: 'BB', name: 'Barbados', flag: '🇧🇧'),
  CountryOption(code: 'BY', name: 'Belarus', flag: '🇧🇾'),
  CountryOption(code: 'BE', name: 'Belgium', flag: '🇧🇪'),
  CountryOption(code: 'BZ', name: 'Belize', flag: '🇧🇿'),
  CountryOption(code: 'BJ', name: 'Benin', flag: '🇧🇯'),
  CountryOption(code: 'BT', name: 'Bhutan', flag: '🇧🇹'),
  CountryOption(code: 'BO', name: 'Bolivia', flag: '🇧🇴'),
  CountryOption(code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦'),
  CountryOption(code: 'BW', name: 'Botswana', flag: '🇧🇼'),
  CountryOption(code: 'BR', name: 'Brazil', flag: '🇧🇷'),
  CountryOption(code: 'BN', name: 'Brunei', flag: '🇧🇳'),
  CountryOption(code: 'BG', name: 'Bulgaria', flag: '🇧🇬'),
  CountryOption(code: 'BF', name: 'Burkina Faso', flag: '🇧🇫'),
  CountryOption(code: 'BI', name: 'Burundi', flag: '🇧🇮'),
  CountryOption(code: 'CV', name: 'Cabo Verde', flag: '🇨🇻'),
  CountryOption(code: 'KH', name: 'Cambodia', flag: '🇰🇭'),
  CountryOption(code: 'CM', name: 'Cameroon', flag: '🇨🇲'),
  CountryOption(code: 'CA', name: 'Canada', flag: '🇨🇦'),
  CountryOption(code: 'CF', name: 'Central African Republic', flag: '🇨🇫'),
  CountryOption(code: 'TD', name: 'Chad', flag: '🇹🇩'),
  CountryOption(code: 'CL', name: 'Chile', flag: '🇨🇱'),
  CountryOption(code: 'CN', name: 'China', flag: '🇨🇳'),
  CountryOption(code: 'CO', name: 'Colombia', flag: '🇨🇴'),
  CountryOption(code: 'KM', name: 'Comoros', flag: '🇰🇲'),
  CountryOption(code: 'CG', name: 'Congo', flag: '🇨🇬'),
  CountryOption(code: 'CR', name: 'Costa Rica', flag: '🇨🇷'),
  CountryOption(code: 'HR', name: 'Croatia', flag: '🇭🇷'),
  CountryOption(code: 'CU', name: 'Cuba', flag: '🇨🇺'),
  CountryOption(code: 'CY', name: 'Cyprus', flag: '🇨🇾'),
  CountryOption(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿'),
  CountryOption(code: 'DK', name: 'Denmark', flag: '🇩🇰'),
  CountryOption(code: 'DJ', name: 'Djibouti', flag: '🇩🇯'),
  CountryOption(code: 'DO', name: 'Dominican Republic', flag: '🇩🇴'),
  CountryOption(code: 'CD', name: 'DR Congo', flag: '🇨🇩'),
  CountryOption(code: 'EC', name: 'Ecuador', flag: '🇪🇨'),
  CountryOption(code: 'EG', name: 'Egypt', flag: '🇪🇬'),
  CountryOption(code: 'SV', name: 'El Salvador', flag: '🇸🇻'),
  CountryOption(code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶'),
  CountryOption(code: 'ER', name: 'Eritrea', flag: '🇪🇷'),
  CountryOption(code: 'EE', name: 'Estonia', flag: '🇪🇪'),
  CountryOption(code: 'SZ', name: 'Eswatini', flag: '🇸🇿'),
  CountryOption(code: 'ET', name: 'Ethiopia', flag: '🇪🇹'),
  CountryOption(code: 'FJ', name: 'Fiji', flag: '🇫🇯'),
  CountryOption(code: 'FI', name: 'Finland', flag: '🇫🇮'),
  CountryOption(code: 'FR', name: 'France', flag: '🇫🇷'),
  CountryOption(code: 'GA', name: 'Gabon', flag: '🇬🇦'),
  CountryOption(code: 'GM', name: 'Gambia', flag: '🇬🇲'),
  CountryOption(code: 'GE', name: 'Georgia', flag: '🇬🇪'),
  CountryOption(code: 'DE', name: 'Germany', flag: '🇩🇪'),
  CountryOption(code: 'GH', name: 'Ghana', flag: '🇬🇭'),
  CountryOption(code: 'GR', name: 'Greece', flag: '🇬🇷'),
  CountryOption(code: 'GD', name: 'Grenada', flag: '🇬🇩'),
  CountryOption(code: 'GT', name: 'Guatemala', flag: '🇬🇹'),
  CountryOption(code: 'GN', name: 'Guinea', flag: '🇬🇳'),
  CountryOption(code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼'),
  CountryOption(code: 'GY', name: 'Guyana', flag: '🇬🇾'),
  CountryOption(code: 'HT', name: 'Haiti', flag: '🇭🇹'),
  CountryOption(code: 'HN', name: 'Honduras', flag: '🇭🇳'),
  CountryOption(code: 'HU', name: 'Hungary', flag: '🇭🇺'),
  CountryOption(code: 'IS', name: 'Iceland', flag: '🇮🇸'),
  CountryOption(code: 'IN', name: 'India', flag: '🇮🇳'),
  CountryOption(code: 'ID', name: 'Indonesia', flag: '🇮🇩'),
  CountryOption(code: 'IR', name: 'Iran', flag: '🇮🇷'),
  CountryOption(code: 'IQ', name: 'Iraq', flag: '🇮🇶'),
  CountryOption(code: 'IE', name: 'Ireland', flag: '🇮🇪'),
  CountryOption(code: 'IL', name: 'Israel', flag: '🇮🇱'),
  CountryOption(code: 'IT', name: 'Italy', flag: '🇮🇹'),
  CountryOption(code: 'JM', name: 'Jamaica', flag: '🇯🇲'),
  CountryOption(code: 'JP', name: 'Japan', flag: '🇯🇵'),
  CountryOption(code: 'JO', name: 'Jordan', flag: '🇯🇴'),
  CountryOption(code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿'),
  CountryOption(code: 'KE', name: 'Kenya', flag: '🇰🇪'),
  CountryOption(code: 'KI', name: 'Kiribati', flag: '🇰🇮'),
  CountryOption(code: 'KW', name: 'Kuwait', flag: '🇰🇼'),
  CountryOption(code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬'),
  CountryOption(code: 'LA', name: 'Laos', flag: '🇱🇦'),
  CountryOption(code: 'LV', name: 'Latvia', flag: '🇱🇻'),
  CountryOption(code: 'LB', name: 'Lebanon', flag: '🇱🇧'),
  CountryOption(code: 'LS', name: 'Lesotho', flag: '🇱🇸'),
  CountryOption(code: 'LR', name: 'Liberia', flag: '🇱🇷'),
  CountryOption(code: 'LY', name: 'Libya', flag: '🇱🇾'),
  CountryOption(code: 'LI', name: 'Liechtenstein', flag: '🇱🇮'),
  CountryOption(code: 'LT', name: 'Lithuania', flag: '🇱🇹'),
  CountryOption(code: 'LU', name: 'Luxembourg', flag: '🇱🇺'),
  CountryOption(code: 'MG', name: 'Madagascar', flag: '🇲🇬'),
  CountryOption(code: 'MW', name: 'Malawi', flag: '🇲🇼'),
  CountryOption(code: 'MY', name: 'Malaysia', flag: '🇲🇾'),
  CountryOption(code: 'MV', name: 'Maldives', flag: '🇲🇻'),
  CountryOption(code: 'ML', name: 'Mali', flag: '🇲🇱'),
  CountryOption(code: 'MT', name: 'Malta', flag: '🇲🇹'),
  CountryOption(code: 'MH', name: 'Marshall Islands', flag: '🇲🇭'),
  CountryOption(code: 'MR', name: 'Mauritania', flag: '🇲🇷'),
  CountryOption(code: 'MU', name: 'Mauritius', flag: '🇲🇺'),
  CountryOption(code: 'MX', name: 'Mexico', flag: '🇲🇽'),
  CountryOption(code: 'FM', name: 'Micronesia', flag: '🇫🇲'),
  CountryOption(code: 'MD', name: 'Moldova', flag: '🇲🇩'),
  CountryOption(code: 'MC', name: 'Monaco', flag: '🇲🇨'),
  CountryOption(code: 'MN', name: 'Mongolia', flag: '🇲🇳'),
  CountryOption(code: 'ME', name: 'Montenegro', flag: '🇲🇪'),
  CountryOption(code: 'MA', name: 'Morocco', flag: '🇲🇦'),
  CountryOption(code: 'MZ', name: 'Mozambique', flag: '🇲🇿'),
  CountryOption(code: 'MM', name: 'Myanmar', flag: '🇲🇲'),
  CountryOption(code: 'NA', name: 'Namibia', flag: '🇳🇦'),
  CountryOption(code: 'NR', name: 'Nauru', flag: '🇳🇷'),
  CountryOption(code: 'NP', name: 'Nepal', flag: '🇳🇵'),
  CountryOption(code: 'NL', name: 'Netherlands', flag: '🇳🇱'),
  CountryOption(code: 'NZ', name: 'New Zealand', flag: '🇳🇿'),
  CountryOption(code: 'NI', name: 'Nicaragua', flag: '🇳🇮'),
  CountryOption(code: 'NE', name: 'Niger', flag: '🇳🇪'),
  CountryOption(code: 'NG', name: 'Nigeria', flag: '🇳🇬'),
  CountryOption(code: 'NO', name: 'Norway', flag: '🇳🇴'),
  CountryOption(code: 'OM', name: 'Oman', flag: '🇴🇲'),
  CountryOption(code: 'PK', name: 'Pakistan', flag: '🇵🇰'),
  CountryOption(code: 'PW', name: 'Palau', flag: '🇵🇼'),
  CountryOption(code: 'PA', name: 'Panama', flag: '🇵🇦'),
  CountryOption(code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬'),
  CountryOption(code: 'PY', name: 'Paraguay', flag: '🇵🇾'),
  CountryOption(code: 'PE', name: 'Peru', flag: '🇵🇪'),
  CountryOption(code: 'PH', name: 'Philippines', flag: '🇵🇭'),
  CountryOption(code: 'PL', name: 'Poland', flag: '🇵🇱'),
  CountryOption(code: 'PT', name: 'Portugal', flag: '🇵🇹'),
  CountryOption(code: 'QA', name: 'Qatar', flag: '🇶🇦'),
  CountryOption(code: 'RO', name: 'Romania', flag: '🇷🇴'),
  CountryOption(code: 'RU', name: 'Russia', flag: '🇷🇺'),
  CountryOption(code: 'RW', name: 'Rwanda', flag: '🇷🇼'),
  CountryOption(code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳'),
  CountryOption(code: 'LC', name: 'Saint Lucia', flag: '🇱🇨'),
  CountryOption(code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨'),
  CountryOption(code: 'WS', name: 'Samoa', flag: '🇼🇸'),
  CountryOption(code: 'SM', name: 'San Marino', flag: '🇸🇲'),
  CountryOption(code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹'),
  CountryOption(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦'),
  CountryOption(code: 'SN', name: 'Senegal', flag: '🇸🇳'),
  CountryOption(code: 'RS', name: 'Serbia', flag: '🇷🇸'),
  CountryOption(code: 'SC', name: 'Seychelles', flag: '🇸🇨'),
  CountryOption(code: 'SL', name: 'Sierra Leone', flag: '🇸🇱'),
  CountryOption(code: 'SG', name: 'Singapore', flag: '🇸🇬'),
  CountryOption(code: 'SK', name: 'Slovakia', flag: '🇸🇰'),
  CountryOption(code: 'SI', name: 'Slovenia', flag: '🇸🇮'),
  CountryOption(code: 'SB', name: 'Solomon Islands', flag: '🇸🇧'),
  CountryOption(code: 'SO', name: 'Somalia', flag: '🇸🇴'),
  CountryOption(code: 'ZA', name: 'South Africa', flag: '🇿🇦'),
  CountryOption(code: 'SS', name: 'South Sudan', flag: '🇸🇸'),
  CountryOption(code: 'ES', name: 'Spain', flag: '🇪🇸'),
  CountryOption(code: 'LK', name: 'Sri Lanka', flag: '🇱🇰'),
  CountryOption(code: 'SD', name: 'Sudan', flag: '🇸🇩'),
  CountryOption(code: 'SR', name: 'Suriname', flag: '🇸🇷'),
  CountryOption(code: 'SE', name: 'Sweden', flag: '🇸🇪'),
  CountryOption(code: 'CH', name: 'Switzerland', flag: '🇨🇭'),
  CountryOption(code: 'SY', name: 'Syria', flag: '🇸🇾'),
  CountryOption(code: 'TW', name: 'Taiwan', flag: '🇹🇼'),
  CountryOption(code: 'TJ', name: 'Tajikistan', flag: '🇹🇯'),
  CountryOption(code: 'TZ', name: 'Tanzania', flag: '🇹🇿'),
  CountryOption(code: 'TH', name: 'Thailand', flag: '🇹🇭'),
  CountryOption(code: 'TL', name: 'Timor-Leste', flag: '🇹🇱'),
  CountryOption(code: 'TG', name: 'Togo', flag: '🇹🇬'),
  CountryOption(code: 'TO', name: 'Tonga', flag: '🇹🇴'),
  CountryOption(code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹'),
  CountryOption(code: 'TN', name: 'Tunisia', flag: '🇹🇳'),
  CountryOption(code: 'TR', name: 'Turkey', flag: '🇹🇷'),
  CountryOption(code: 'TM', name: 'Turkmenistan', flag: '🇹🇲'),
  CountryOption(code: 'TV', name: 'Tuvalu', flag: '🇹🇻'),
  CountryOption(code: 'UG', name: 'Uganda', flag: '🇺🇬'),
  CountryOption(code: 'UA', name: 'Ukraine', flag: '🇺🇦'),
  CountryOption(code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪'),
  CountryOption(code: 'GB', name: 'United Kingdom', flag: '🇬🇧'),
  CountryOption(code: 'US', name: 'United States', flag: '🇺🇸'),
  CountryOption(code: 'UY', name: 'Uruguay', flag: '🇺🇾'),
  CountryOption(code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿'),
  CountryOption(code: 'VU', name: 'Vanuatu', flag: '🇻🇺'),
  CountryOption(code: 'VE', name: 'Venezuela', flag: '🇻🇪'),
  CountryOption(code: 'VN', name: 'Vietnam', flag: '🇻🇳'),
  CountryOption(code: 'YE', name: 'Yemen', flag: '🇾🇪'),
  CountryOption(code: 'ZM', name: 'Zambia', flag: '🇿🇲'),
  CountryOption(code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼'),
];

/// Finds a [CountryOption] by ISO alpha-2 code, returns null if not found.
CountryOption? countryByCode(String code) {
  try {
    return kCountries.firstWhere(
      (c) => c.code.toUpperCase() == code.toUpperCase(),
    );
  } catch (_) {
    return null;
  }
}
